### ISSUE TITLE
How SORT function is working in this program?

### ISSUE THREAD

**Issue by pawwi** [mburst/dijkstras-algorithm#10]
> nodes.Sort((x, y) => distances[x] -  distances[y]);

What is this line in the program is doing. Yes i know that it is sorting the list Nodes but the statement inside the brackets. Can anybody tell me how this line is working in program in detail.

**Comment by mburst** [comment]
It's being used instead of using a min heap. You can read about how it works here http://www.maxburstein.com/blog/introduction-to-graph-theory-finding-shortest-path/
