### ISSUE TITLE
How to operate on 2d array

### ISSUE THREAD

**Issue by MurhafSousli** [mburst/dijkstras-algorithm#12]
Hi, I'm wondering if I can use this algorithm for a 2d array, I have a `matrix: Node[][]`, and I'm trying to get the shortest route between 2 points

```javascript
class Node{
   index: {
     x: number,
     y: number
   },
   isAvailable: boolean        //trees are false
}
```
![capture](https://cloud.githubusercontent.com/assets/8130692/20694806/7f56d246-b5f0-11e6-8fc5-3af806a18231.PNG)

I tried this, but doesn't seem that I'm filling the graph correctly
```javascript

const graph = new Dijkstra();

//convert the matrix (2d array) to graph
matrix.map((row) => {
  row.map((node: Node) => {
     let x = node.index.x;
     let y = node.index.y;
     graph.addVertex(x + ":" + y, {x: x, y: y}); 
  });
});
console.log(graph.shortestPath('0:0', '5:5'));
//output is ["0:0"]
```
Is it possible to get the shortest path using the algorithm?

**Comment by mburst** [comment]
You totally can. You just need to think of each square as a node on the graph with a distance of 1. You'd skip adding the trees as nodes on the list in the above example
