### ISSUE TITLE
How can I use this algoritm into graph directed

### ISSUE THREAD

**Issue by brunoheringer** [mburst/dijkstras-algorithm#18]
How can I use this algorithm into graph directed?

Hello, I would like to use this algorithm, but, I would like to add a feature of "direction". It is possible?

**Comment by mburst** [comment]
Unfortunately that's beyond the scope of the tutorials I have covered and this code repository. This may be of use to you http://www.geeksforgeeks.org/shortest-path-for-directed-acyclic-graphs/
