### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by n1x0id** [mburst/dijkstras-algorithm#7]
Java
System.out.println(g.getShortestPath('B', 'A'));
[A, B, C, D, E, F, G, H]
WTH?

And many errors:
A -> B
[B]

A -> C
[C]

A -> D
[D, F, B]

A -> E
[E, H, F, B]

A -> F
[F, B]

A -> G
[G, C]

A -> H
[H, F, B]

B -> A
[A, B, C, D, E, F, G, H]

B -> C
[]

B -> D
[A, B, C, D, E, F, G, H]

B -> E
[A, B, C, D, E, F, G, H]

B -> F
[A, B, C, D, E, F, G, H]

B -> G
[A, B, C, D, E, F, G, H]

B -> H
[A, B, C, D, E, F, G, H]

C -> A
[A]

C -> B
[B, F]

C -> D
[D, F]

C -> E
[E, H, F]

C -> F
[F]

C -> G
[G]

C -> H
[H, F]

D -> A
[A, B, C, D, E, F, G, H]

D -> B
[A, B, C, D, E, F, G, H]

D -> C
[]

D -> E
[A, B, C, D, E, F, G, H]

D -> F
[A, B, C, D, E, F, G, H]

D -> G
[A, B, C, D, E, F, G, H]

D -> H
[A, B, C, D, E, F, G, H]

E -> A
[A, B, C, D, E, F, G, H]

E -> B
[A, B, C, D, E, F, G, H]

E -> C
[]

E -> D
[A, B, C, D, E, F, G, H]

E -> F
[A, B, C, D, E, F, G, H]

E -> G
[A, B, C, D, E, F, G, H]

E -> H
[A, B, C, D, E, F, G, H]

F -> A
[]

F -> B
[A, B, C, D, E, F, G, H]

F -> C
[A, B, C, D, E, F, G, H]

F -> D
[A, B, C, D, E, F, G, H]

F -> E
[A, B, C, D, E, F, G, H]

F -> G
[A, B, C, D, E, F, G, H]

F -> H
[A, B, C, D, E, F, G, H]

G -> A
[]

G -> B
[A, B, C, D, E, F, G, H]

G -> C
[A, B, C, D, E, F, G, H]

G -> D
[A, B, C, D, E, F, G, H]

G -> E
[A, B, C, D, E, F, G, H]

G -> F
[A, B, C, D, E, F, G, H]

G -> H
[A, B, C, D, E, F, G, H]

H -> A
[A, B, C, D, E, F, G, H]

H -> B
[A, B, C, D, E, F, G, H]

H -> C
[]

H -> D
[A, B, C, D, E, F, G, H]

H -> E
[A, B, C, D, E, F, G, H]

H -> F
[A, B, C, D, E, F, G, H]

H -> G
[A, B, C, D, E, F, G, H]

**Comment by mburst** [comment]
Not sure how I missed this ticket but definitely feel free to submit a PR for it or perhaps @kinow can help

**Comment by kinow** [comment]
I think I found the issue. Wasn't taking care of updating the priority queue. Whenever the distance was updated, the priority queue (at least in Java) needs to be updated, i.e. an element needs to be removed and added back to the data structure.

Examples:

```
	System.out.println(g.getShortestPath('A', 'B'));
	System.out.println(g.getShortestPath('A', 'C'));
	System.out.println(g.getShortestPath('A', 'D'));
	System.out.println(g.getShortestPath('A', 'E'));
	System.out.println(g.getShortestPath('A', 'F'));
        System.out.println(g.getShortestPath('A', 'G'));
        System.out.println(g.getShortestPath('A', 'H'));

        System.out.println(g.getShortestPath('B', 'A'));
        System.out.println(g.getShortestPath('B', 'C'));
        System.out.println(g.getShortestPath('B', 'D'));
        System.out.println(g.getShortestPath('B', 'E'));
        System.out.println(g.getShortestPath('B', 'F'));
        System.out.println(g.getShortestPath('B', 'G'));
        System.out.println(g.getShortestPath('B', 'H'));
        
        System.out.println(g.getShortestPath('C', 'A'));
        System.out.println(g.getShortestPath('C', 'B'));
        System.out.println(g.getShortestPath('C', 'D'));
        System.out.println(g.getShortestPath('C', 'E'));
        System.out.println(g.getShortestPath('C', 'F'));
        System.out.println(g.getShortestPath('C', 'G'));
        System.out.println(g.getShortestPath('C', 'H'));
        
        System.out.println(g.getShortestPath('D', 'A'));
        System.out.println(g.getShortestPath('D', 'B'));
        System.out.println(g.getShortestPath('D', 'C'));
        System.out.println(g.getShortestPath('D', 'E'));
        System.out.println(g.getShortestPath('D', 'F'));
        System.out.println(g.getShortestPath('D', 'G'));
        System.out.println(g.getShortestPath('D', 'H'));
        
        System.out.println(g.getShortestPath('E', 'A'));
        System.out.println(g.getShortestPath('E', 'B'));
        System.out.println(g.getShortestPath('E', 'C'));
        System.out.println(g.getShortestPath('E', 'D'));
        System.out.println(g.getShortestPath('E', 'F'));
        System.out.println(g.getShortestPath('E', 'G'));
        System.out.println(g.getShortestPath('E', 'H'));
        
        System.out.println(g.getShortestPath('F', 'A'));
        System.out.println(g.getShortestPath('F', 'B'));
        System.out.println(g.getShortestPath('F', 'C'));
        System.out.println(g.getShortestPath('F', 'D'));
        System.out.println(g.getShortestPath('F', 'E'));
        System.out.println(g.getShortestPath('F', 'G'));
        System.out.println(g.getShortestPath('F', 'H'));
        
        System.out.println(g.getShortestPath('G', 'A'));
        System.out.println(g.getShortestPath('G', 'B'));
        System.out.println(g.getShortestPath('G', 'C'));
        System.out.println(g.getShortestPath('G', 'D'));
        System.out.println(g.getShortestPath('G', 'E'));
        System.out.println(g.getShortestPath('G', 'F'));
        System.out.println(g.getShortestPath('G', 'H'));
        
        System.out.println(g.getShortestPath('H', 'A'));
        System.out.println(g.getShortestPath('H', 'B'));
        System.out.println(g.getShortestPath('H', 'C'));
        System.out.println(g.getShortestPath('H', 'D'));
        System.out.println(g.getShortestPath('H', 'E'));
        System.out.println(g.getShortestPath('H', 'F'));
        System.out.println(g.getShortestPath('H', 'G'));
```

Will output now:

```
[B]
[C]
[D, F, B]
[E, H, F, B]
[F, B]
[G, C]
[H, F, B]
[A]
[C, F]
[D, F]
[E, H, F]
[F]
[G, F]
[H, F]
[A]
[B, F]
[D, F]
[E, H, F]
[F]
[G]
[H, F]
[A, B, F]
[B, F]
[C, F]
[E, H, F]
[F]
[G, F]
[H, F]
[A, B, F, H]
[B, F, H]
[C, F, H]
[D, F, H]
[F, H]
[G, F, H]
[H]
[A, B]
[B]
[C]
[D]
[E, H]
[G]
[H]
[A, C]
[B, F]
[C]
[D, F]
[E, H, F]
[F]
[H, F]
[A, B, F]
[B, F]
[C, F]
[D, F]
[E]
[F]
[G, F]
```

I think it looks correct now? Reviewed the code comparing to the Python implementation and blog post too.

**Comment by mburst** [comment]
Thanks for the quick response! Make a PR. Would love to get it updated
