### ISSUE TITLE
How to addVertex from array

### ISSUE THREAD

**Issue by nabrih** [mburst/dijkstras-algorithm#8]
Hi, please help me to insert value from an array to Graph

**Comment by mburst** [comment]
What language file are you looking at?

**Comment by nabrih** [comment]
I use JavaScript for this

**Comment by mburst** [comment]
You just need to call add vertex https://github.com/mburst/dijkstras-algorithm/blob/master/dijkstras.js#L33

**Comment by nabrih** [comment]
thanks its done.

and can this algorithm get top 3 possibility of shortest way?

**Comment by mburst** [comment]
Definitely a tough problem but I'll leave that as an exercise for the user. Marking as close since you were able to get your issue resolved.

Cheers!
